coverage:
  range: "90...100"

ignore:
  - "gpflow/training/*.py"
  - "gpflow/params/*.py"
  - "gpflow/core/autoflow.py"
  - "gpflow/core/tensor_converter.py"
  - "gpflow/misc.py"
  - "gpflow/likelihoods.py"
  - "setup.py"
